# Generated by Django 5.0.4 on 2024-04-08 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeteorologicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MeteorologicalAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('meteorological_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather_forecast.meteorologicalservice')),
            ],
        ),
    ]
