# Generated by Django 5.0.4 on 2024-05-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_forecast', '0002_meteorologicalapi_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meteorologicalservice',
            name='link',
        ),
        migrations.AddField(
            model_name='meteorologicalservice',
            name='foundation_year',
            field=models.PositiveSmallIntegerField(default=1962),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meteorologicalservice',
            name='official_url',
            field=models.URLField(default='https://openweathermap.org'),
            preserve_default=False,
        ),
    ]
