# Generated by Django 5.0.4 on 2024-05-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_forecast', '0004_meteorologicalparameter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meteorologicalapi',
            options={'verbose_name': 'Метеорологический API', 'verbose_name_plural': 'Метеорологические API'},
        ),
        migrations.AlterModelOptions(
            name='meteorologicalparameter',
            options={'verbose_name': 'Метеорологический параметр', 'verbose_name_plural': 'Метеорологические параметры'},
        ),
        migrations.AlterModelOptions(
            name='meteorologicalservice',
            options={'verbose_name': 'Метеорологическая служба', 'verbose_name_plural': 'Метеорологические службы'},
        ),
        migrations.AddField(
            model_name='meteorologicalparameter',
            name='weather_time',
            field=models.CharField(choices=[('Сейчас', 'Сейчас'), ('Прогноз', 'Прогноз')], default='Сейчас', max_length=20, verbose_name='Время погоды'),
            preserve_default=False,
        ),
    ]
