# Generated by Django 5.0.4 on 2024-05-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_forecast', '0005_alter_meteorologicalapi_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteorologicalparameter',
            name='importance',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Важность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meteorologicalparameter',
            name='weather_time',
            field=models.CharField(choices=[('Прогноз', 'Прогноз'), ('Сейчас', 'Сейчас')], max_length=20, verbose_name='Время погоды'),
        ),
    ]
