# Generated by Django 5.0.4 on 2024-05-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_forecast', '0006_meteorologicalparameter_importance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteorologicalservice',
            name='weather_time',
            field=models.CharField(default='Сейчас', max_length=30, verbose_name='Время погоды'),
            preserve_default=False,
        ),
    ]
