# Generated by Django 5.0.4 on 2024-05-13 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_forecast', '0007_meteorologicalservice_weather_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meteorologicalservice',
            name='weather_time',
        ),
        migrations.CreateModel(
            name='WeatherTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('meteorological_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather_forecast.meteorologicalservice', verbose_name='Метеорологическая служба')),
            ],
            options={
                'verbose_name': 'Время погоды',
                'verbose_name_plural': 'Время погоды',
            },
        ),
    ]
