# Generated by Django 5.0.4 on 2024-05-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_forecast', '0008_remove_meteorologicalservice_weather_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathertime',
            name='meteorological_service',
        ),
        migrations.AddField(
            model_name='meteorologicalservice',
            name='weather_time',
            field=models.ManyToManyField(to='weather_forecast.weathertime', verbose_name='Время погоды'),
        ),
    ]
